services:
  customer-service:
    build:
      context: customer-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  transaction-service:
    build:
      context: transaction-service
      dockerfile: Dockerfile
    hostname: transaction-service
    ports:
      - 8081:8081
