server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    user: sa
    password: password
  main:
    allow-bean-definition-overriding: true
management:
  endpoint:
    health:
      show-details: always
springdoc:
  api-docs:
    path: /api-docs